include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_single_quotes
    - always_use_package_imports
    - prefer_final_fields
